# Generated by Django 4.2.18 on 2025-01-19 19:45

import Guest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
                ('student_contact', models.CharField(max_length=255)),
                ('student_address', models.CharField(max_length=255)),
                ('student_password', models.CharField(max_length=255)),
                ('student_photo', models.FileField(upload_to=Guest.models.student_photo_upload_to)),
            ],
        ),
    ]
